Task_1_1_3
ptntsv/OOP pull request #10
Opened 2024-10-01 04:42 UTC by ptntsv

2024-10-02 11:25 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн зачтён, доделывайте

Если планируете выполнять доп. условия, напишите об этом

2024-10-02 11:25 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/example/Expressions/Expression.java
> +    public Expression right;
А всем ли наследникам нужны поля `left`, `right`, `opSign`? И всем ли нужно `value`? Надо унести поля тем наследникам, которым они нужны, а в абстрактном классе оставить только приватные, нужные именно в этом классе

2024-10-02 11:25 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/example/Expressions/Expression.java
> +public abstract class Expression {
Нужно расставить на всех полях и методах правильные модификаторы доступа, инкапсулировать детали реализации и оставить внешним пользователям классов только нужные методы

2024-10-02 11:25 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/example/Lexer/OperationToken.java
> +    public OperationToken(OpType type, String content, int p, Associativity as) {
Аргументы конструктора надо бы поразвёрнутее назвать

2024-10-02 11:25 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/example/Expressions/Expression.java
> +    public static Expression deserialize(Scanner reader) {
По заданию должен быть какой-то способ по строке построить выражение, нужно будет доделать

2024-10-02 13:48 UTC, ptntsv commented on Task_1_1_3/src/main/java/org/example/Lexer/OperationToken.java
> +    public OperationToken(OpType type, String content, int p, Associativity as) {
Done

2024-10-02 13:51 UTC, ptntsv commented on Task_1_1_3/src/main/java/org/example/Expressions/Expression.java
> +    public static Expression deserialize(Scanner reader) {
Хм, кажется, `deserialize` этим и занимается.

2024-10-02 13:52 UTC, ptntsv commented on Task_1_1_3/src/main/java/org/example/Expressions/Expression.java
> +public abstract class Expression {
Done.

2024-10-02 13:52 UTC, ptntsv commented on Task_1_1_3/src/main/java/org/example/Expressions/Expression.java
> +    public Expression right;
Done.

2024-10-03 17:23 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/example/Expressions/Expression.java
> +    public static Expression deserialize(Scanner reader) {
Мне показалось неудобным использование `Scanner` в качестве аргумента, я ожидал увидеть здесь просто `String`. Но действительно, ваша реализация не противоречит условию задачи, замечание не актуально

2024-10-07 16:42 UTC, Sharapov-Maksim requested changes
Замечания выдал + GitHub Actions / reviewdog ругается на отсутствие javadoc и неправильные имена пакетов

2024-10-07 16:42 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/example/Expressions/Expression.java
> +        return parseExpression(tokens);
Можно заменить на `deserialize(expr)`

2024-10-07 16:42 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/example/Expressions/Expression.java
> +    }
Протестировать

2024-10-07 16:42 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/LexerTest.java
> +        Assertions.assertEquals(tokens.size(), 1);
Посмотрите на сигнатуру `assertEquals`, сначала идёт `expected` а потом `actual` а у вас наоборот аргументы передаются

2024-10-08 03:56 UTC, ptntsv commented on Task_1_1_3/src/main/java/org/example/Expressions/Expression.java
> +        return parseExpression(tokens);
Done.

2024-10-08 03:56 UTC, ptntsv commented on Task_1_1_3/src/test/java/LexerTest.java
> +        Assertions.assertEquals(tokens.size(), 1);
Done.

2024-10-08 04:45 UTC, ptntsv commented on Task_1_1_3/src/main/java/org/example/Expressions/Expression.java
> +    }
Done.

2024-10-08 11:18 UTC, Sharapov-Maksim requested changes
Оставшиеся замечания checkstyle надо исправить

2024-10-08 11:18 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/example/expressions/Expression.java
> +    public abstract Expression derivative(String var);
Протестировать для всех наследников

2024-10-08 11:18 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/example/lexer/Token.java
> +    }
Unused?

2024-10-08 11:18 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/org/example/expressions/Expression.java
> +                        }
Здесь можно добавить в конце
```
default:
    throw new UnsupportedOperationException("Unsupported operation type: " + op.type);
```
Так, если кто-то добавит новый `OpType` и забудет его здесь обработать, исключение об этом напомнит

2024-10-08 14:36 UTC, Sharapov-Maksim approved these changes
Задание зачтено, доп. баллы: 2
PR можно мёржить

2024-10-08 15:46 UTC, merged