Task_1_2_1
ptntsv/OOP pull request #11
Opened 2024-10-15 12:14 UTC by ptntsv

2024-10-15 15:11 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн зачтён, доделывайте

2024-10-15 15:11 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/GraphDeserializer.java
> +}
Что-то у вас какие-то лишние классы в решении лежат

2024-10-15 15:11 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AdjMatrixGraph.java
> +    protected HashMap<Vertex<T>, HashMap<Vertex<T>, Boolean>> adjMatrix = new HashMap<>();
Нужно будет переделать на массивы или, на крайний случай, `ArrayList`

2024-10-15 15:11 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/IGraph.java
> +}
Нужно будет описать в javadoc поведение методов

2024-10-15 15:11 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/IncidenceMatrixGraph.java
> +    protected HashMap<Vertex<T>, HashMap<Edge<T>, Integer>> incMatrix = new HashMap<>();
Аналогично, матрицу хеш-таблицами представлять не надо

2024-10-22 10:13 UTC, Sharapov-Maksim requested changes

2024-10-22 10:13 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/example/Main.java
> +public class Main {
Лишний класс

2024-10-22 10:13 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/Graph.java
> +public class Graph<T> implements IGraph<T> {
Что-то у вас сложная получилась иерархия наследования. Как я понял смысл этого класса, вы хотите сделать переход от `T` к `Integer`, так как конкретные реализации работают с `Integer`.

Больше всего меня смущает конструктор, который вынужден знать о всех реализациях. То есть для добавления новой реализации будет не достаточно просто имплементировать интерфейс, нужно будет зарегистировать новый класс в `GraphRepresentation` и расширить конструктор `Graph`.

Я вижу у класса `Graph` несколько составляющих:
1. Преобразование `T <-> Integer`. Можно вынести в реализации, так как это вполне деталь реализации. Другие представления графа смогут не обязательно использовать `VerticesMapsPair`.
2. Обёртка над реализацией. Станет не нужна если выполнить пункт 1. 

Поэтому предлагаю избавиться от этого класса, а поле `maps` продублировать в каждой реализации.

2024-10-22 10:13 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractIntGraph.java
> +public abstract class AbstractIntGraph implements IGraph<Integer> {
Во всех местах `AbstractIntGraph` можно было бы заменить на `IGraph<Integer>`. Но после удаления `Graph<T>` все реализации будут уже `implements IGraph<T>`

2024-10-22 10:13 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/Graph.java
> +    public List<T> toposort() {
По заданию, нужен (статический) метод, принимающим произвольный `IGraph` и выполняющий на нём сортировку не зависящую от реализации, использующую только методы из интерфейса

2024-10-22 10:13 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AdjMatrixIntGraph.java
> +    }
А вам не кажется странным, что метод не использует аргумент никак кроме `return v`?

2024-10-22 10:13 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AdjMatrixIntGraph.java
> +        }
Перекопировать матрицу на каждом добавлении вершины приведёт к большой алгоритмической сложности операции. Давайте увеличивать матрицу в разы, но лишь иногда, как на алгоритмах учили

2024-10-22 10:13 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/IGraph.java
> +public interface IGraph<T> {
Надо к каждому методу прописать поведение в краевых случаях, и чтобы все реализации соответствовали этому описанию

2024-10-22 10:13 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/IncMatrixIntGraph.java
> +            throw new NoSuchVertexException("Invalid vertex is provided into removeVertex");
`"Invalid vertex " + v + " is ..."`

Предлагаю у `NoSuchVertexException` сделать конструктор который бы принимал строковое представление вершины и генерировал нужное сообщение сам. Тогда во всех подобных местах не будет дублирования сообщений исключения

2024-10-22 10:13 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/IncMatrixIntGraph.java
> +        }
Аналогично `AdjMatrixIntGraph`, перекопировать нужно реже, чем на каждом добавлении вершины/ребра

2024-10-22 10:13 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/IGraph.java
> +public interface IGraph<T> {
По заданию нужны ещё операции сравнения на равенство и вывода в строку

2024-10-22 10:33 UTC, Sharapov-Maksim requested changes

2024-10-22 10:33 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/IncMatrixIntGraph.java
> +    public Integer removeVertex(Integer v) {
Протестировать

2024-10-22 16:56 UTC, Sharapov-Maksim requested changes
Исправить все выданные замечания

2024-10-27 06:19 UTC, Sharapov-Maksim requested changes
+ поправить checkstyle / reviewdog замечания

2024-10-27 06:19 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +    }
Протестировать

2024-10-27 06:19 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AdjListGraph.java
> +    }
Протестировать

2024-10-27 06:19 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/Matrix.java
> +public class Matrix {
javadoc во всём классе

2024-10-27 06:19 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +        Matrix m2 = new Matrix(another.getVerticesN(), another.getVerticesN(), 0);
Создавать вспомогательные матрицы на каждом `equals` не эффективно

2024-10-27 06:19 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +    public boolean equals(Object obj) {
Вынесите equals в интерфейс и сделайте обобщённую реализацию, сравнивающую **содержимое произвольных** графов с помощью методов из интерфейса

2024-10-27 06:19 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +    public static List<Pair<Integer, Integer>> deserialize(String str) {
Метод возвращает не граф, а список. Надо бы поправить описание

2024-10-27 06:19 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +    public static List<Pair<Integer, Integer>> deserialize(String str) {
Всё ещё нужен метод для чтения графа из файла в интерфейсе. А реализация у каждого представления может быть своя, с вызовом вот этого `deserialize`

2024-10-27 06:19 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/Toposort.java
> +    public static <T> List<T> toposort(IGraph<T> graph) {
javadoc, название алгоритма

2024-10-27 06:19 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/VerticesMapsPair.java
> +    }
unused

2024-10-27 06:19 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +        AbstractGraph another = (AbstractGraph) obj;
А если `obj` это не `AbstractGraph`? Тут же может любой объект прийти - полетит исключение, а такого поведения нет в javadoc к `Object.equals`.
`equals` обычно начинают с типовых проверок, например, можете посмотреть как это реализовано в `java.util.Hashtable#equals` (который следует описанию из `java.util.Map#equals`)

2024-10-27 06:19 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/Matrix.java
> +        boolean needCopy = rows + nrows >= rowsCapacity || columns + ncolumns >= columnsCapacity;
`rows + nrows >= rowsCapacity` и `columns + ncolumns >= columnsCapacity` лучше выделить в переменные, так как потом эти выражения снова используются

2024-10-27 06:19 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AdjMatrixGraph.java
> +    }
Здесь возникает неявная зависимость на реализацию `maps.insert`, в которой делается `N++`.
Если бы кто-то решил изменить `VerticesMapsPair` и делать там `N+=2` или сделать переиспользование удалённых индексов, то пришлось бы переделывать все реализации `addVertex`, так как они не пользуются произвольным новым индексом явно, а затачиваются на конкретное изменение индекса в другом классе.

Нужно сделать так, чтобы возникший в `maps.insert` новый индекс использовался. Вместо `adjMatrix.extend` можно сделать условный `adjMatrix.ensureCapacity`, который бы удостоверился, что место под такой индекс есть

2024-10-27 06:52 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +    public boolean equals(Object obj) {
У меня не вышло иначе, ошибка в компайл тайме которую я не смог решить

2024-10-27 07:03 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +    public boolean equals(Object obj) {
Ага, да, я немого ошибся. В интерфес нужно добавить метод без реализации, но с javadoc, в котором описывается что одинаковые графы в разных представлениях равны. Реализацию тогда можно оставить сдесь, но приводить `obj` к `IGraph` и пользоваться общими методам

2024-10-27 08:18 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/AdjMatrixGraph.java
> +    }
А никто и не должен быть способен как-то взаимодействовать с `VerticesMapsPair`, он везде приватный, то, что внутри моего графа какой-то маппер на инты знаю только я, а не пользователь графа.

2024-10-27 08:22 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +    }
А как тестировать то, что выводится в консоль? Я потестировал, вроде работает

2024-10-27 13:17 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +    }
А вы лучше переделайте чтобы строка возвращалась, это будет блише к условиям задачи

2024-10-27 13:22 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AdjMatrixGraph.java
> +    }
У вас классы реализаций надеются на поведение мапы, которое никак не описано, по сути затачиваясь на её реализацию. Если **вы** измените реализацию маппера, **вам** придётся ещё и реализации графов исправлять, так что нкжно зафиксировать интерфейс взаимодействия этих классов

2024-10-27 15:14 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/AdjMatrixGraph.java
> +    }
То есть, грубо говоря, нужно решать на какой индекс замаппить новую вершину не в каком-то стороннем классе, а в этом же (то есть в классе реализации?)

2024-10-28 07:07 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AdjMatrixGraph.java
> +    }
Решать можно и в другом классе, но нужно воспользоваться полученным выделенным индексом, логично же?

2024-10-28 16:14 UTC, Sharapov-Maksim requested changes
Подчистить код (checkstyle / reviewdog, закомментированный код).
Исправить не исправленные прошлые замечания. Вообще не очень-то красиво их игнорировать и запрашивать ревью, оно так может и досрочно закончиться...

2024-10-28 16:14 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/IGraph.java
> +public interface IGraph<T> {
Добавить методы `equals` и `toString`, как того требует задание

2024-10-28 16:14 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/Matrix.java
> +    public void extend(int nrows, int ncolumns) {
unused

2024-10-28 16:14 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +                    List<Integer> this_vs = getAdjacent(maps.getIntTHashMap().get(another.maps.gettIntHashMap().get(v)))
А зачем так сложно? Можно же было просто множества смежных вершин (типа `T`) сравнить, не преобразуя их в индексы. К тому же при использовании `List`ов ещё и зависимость от порядка остаётся.
```
Set<T> a_vs = new HashSet<>(getAdjacent(v));
Set<T> this_vs = new HashSet<>(getAdjacent(v));
if (!this_vs.equals(a_vs)) {
    return false;
}
```
И рекомендую ознакомиться с javadoc к `Set.equals()`

2024-10-28 16:14 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +                var another = (AbstractGraph<T>) ag;
`(IGraph<T>) ag`

После исправления предыдущего замечания это становится возможным, так как получилось избавиться от зависимости от `maps`.

2024-10-28 16:14 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +                    }
`another` граф надо же тоже проверить? Добавьте соответствующий метод в интерфейс, и используйте его тут

2024-10-28 16:14 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/Toposort.java
> +    public static <T> List<T> toposort(IGraph<T> graph) {
Название у алгоритма есть?

2024-10-28 16:14 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/Matrix.java
> +        columns++;
A `rows` и `columns` разве не должны стать `xindex` и `yindex`? Вы же для них место выделяли

2024-10-28 16:14 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/Matrix.java
> +        boolean needCopy = xindex >= rowsCapacity || yindex >= columnsCapacity;
(`xindex`, `yindex`) -> (`newRows`, `newCols`)? Чтобы логичнее было

И помните про [переменные](https://github.com/ptntsv/OOP/pull/11#discussion_r1817989594)

2024-10-29 02:40 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/IGraph.java
> +public interface IGraph<T> {
Done

2024-10-29 02:40 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/Matrix.java
> +    public void extend(int nrows, int ncolumns) {
Done

2024-10-29 02:40 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +                    List<Integer> this_vs = getAdjacent(maps.getIntTHashMap().get(another.maps.gettIntHashMap().get(v)))
Done

2024-10-29 02:40 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +                var another = (AbstractGraph<T>) ag;
Done

2024-10-29 02:41 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +                    }
Done

2024-10-29 02:41 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/Toposort.java
> +    public static <T> List<T> toposort(IGraph<T> graph) {
Done

2024-10-29 02:41 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/Matrix.java
> +        columns++;
Done

2024-10-29 02:41 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/Matrix.java
> +        boolean needCopy = xindex >= rowsCapacity || yindex >= columnsCapacity;
Done

2024-10-29 16:50 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +    public String toString() {
[Протестировать](https://github.com/ptntsv/OOP/pull/11#discussion_r1817986085)...

2024-10-29 16:50 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +                    if (anotherVertices.size() != thisVertices.size() || !thisVertices.equals(
Проверка на размеры и так подразумевается под `thisVertices.equals(anotherVertices)`, но как хотите

2024-10-29 16:50 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +                    Set<T> thisVertices = new HashSet<>(getAdjacent(v));
Обработать `NoSuchVertexException`? Или вернуть проверку на наличие вершины

2024-10-29 16:50 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/Toposort.java
> +    public static <T> List<T> toposort(IGraph<T> graph) {
Видимо нет =(

2024-10-29 17:00 UTC, Sharapov-Maksim requested changes

2024-10-29 17:00 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +    public static List<Pair<Integer, Integer>> deserialize(String str) {
[1](https://github.com/ptntsv/OOP/pull/11/files#r1817987873), [2](https://github.com/ptntsv/OOP/pull/11/files#r1817988122)

2024-10-29 17:03 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +                    Set<T> thisVertices = new HashSet<>(getAdjacent(v));
Ошибка кстати возникла из-за отсутсвия тестов на `equals() == false`

2024-10-29 17:04 UTC, Sharapov-Maksim requested changes

2024-10-29 17:04 UTC, Sharapov-Maksim commented on Task_1_2_1/src/test/java/org/graph/GraphEqualityTest.java
> +public class GraphEqualityTest {
Сделать тесты на неравенство

2024-10-31 02:53 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +                    if (anotherVertices.size() != thisVertices.size() || !thisVertices.equals(
Done

2024-10-31 02:53 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +                    Set<T> thisVertices = new HashSet<>(getAdjacent(v));
Done

2024-10-31 03:06 UTC, ptntsv commented on Task_1_2_1/src/test/java/org/graph/GraphEqualityTest.java
> +public class GraphEqualityTest {
Done

2024-10-31 03:06 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +    public String toString() {
Done

2024-10-31 03:39 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/AbstractGraph.java
> +    public static List<Pair<Integer, Integer>> deserialize(String str) {
Done

2024-11-03 05:13 UTC, Sharapov-Maksim requested changes
Напоследок, опишите, как добавить в имеющуюся объектную модель новый способ
представления графа

2024-11-03 05:13 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/org/graph/Graph.java
> +    List<T> getAdjacent(T v);
> If graph doesn't contain provided vertex then empty list will be returned

Сделайте тесты на этот сценарий. Сейчас там летит `NullPointerException`

2024-11-03 14:29 UTC, ptntsv commented on Task_1_2_1/src/main/java/org/graph/Graph.java
> +    List<T> getAdjacent(T v);
Добавляем класс с новым представлением, наследуемся от абстрактного класса `AbstractGraph`, реализовываем все необходимые методы, по идее, всё

2024-11-04 04:56 UTC, Sharapov-Maksim approved these changes
Задание зачтено

2024-11-28 02:25 UTC, merged