Task_1_3_1
ptntsv/OOP pull request #12
Opened 2024-11-10 10:05 UTC by ptntsv

2024-11-11 07:12 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн зачтён

2024-11-11 07:12 UTC, Sharapov-Maksim commented on Task_1_3_1/src/main/java/org/example/Main.java
> +            return null;
`return null` лучше убрать и перебросить исключение пользователю, и добавить это в javadoc. Так пользователь вашего условно-библиотечного класса сможет сам решать, что делать с ошибкой.

2024-11-11 07:12 UTC, Sharapov-Maksim commented on Task_1_3_1/src/main/java/org/example/Main.java
> +    public static List<Integer> find(String filePath, String subStr, char delimiter) {
`delimeter` - это ведь деталь реализации, специфичная для конкретного алгоритма? Думаю не стоит выносить эту деталь в публичное API. Стоит либо самостоятельно найти нужный `delimeter`, либо хотя бы в процессе поиска проверять, что в файле действительно нет такого символа. К тому же, KMP можно реализовать и без delimeter

2024-11-11 07:12 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/FindTest.java
> +public class FindTest {
> размер входного файла может быть во много раз больше объема оперативной памяти вычислительного устройства, а размер искомой подстроки — во много раз меньше;

Давайте подобный тест добавите, где файл в несколько раз больше свободной памяти под кучу. 
И попробуйте провести эксперимент: запустить данный тест с ограниченным размером кучи (см. -Xmx VM option, например: `-Xmx256m` для файла в 1GB. Или `maxHeapSize = '256m'` в `build.gradle`), проверить, что он не падает с OutOfMemory. При этом стоит сделать тест так, чтобы не раздувать список `ans`, желательно чтобы найденное вхождение было одно или их не было вовсе. Об условиях и результатах эксперимента напишите комментарий =)

2024-11-11 07:12 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/FindTest.java
> +        assert ans != null;
Такие `assert`'ы не относятся к JUnit и работают только при выставлении VM option `-ea`. Давайте заменим на `Assertions.assertNotNull(...)`

2024-11-11 13:52 UTC, ptntsv commented on Task_1_3_1/src/test/java/FindTest.java
> +        assert ans != null;
Done

2024-11-11 13:52 UTC, ptntsv commented on Task_1_3_1/src/test/java/FindTest.java
> +public class FindTest {
Работает
![image](https://github.com/user-attachments/assets/1fc1d226-1786-42f9-abf5-8d00e325badf)

2024-11-11 13:52 UTC, ptntsv commented on Task_1_3_1/src/main/java/org/example/Main.java
> +    public static List<Integer> find(String filePath, String subStr, char delimiter) {
Done

2024-11-11 13:52 UTC, ptntsv commented on Task_1_3_1/src/main/java/org/example/Main.java
> +            return null;
Done

2024-11-11 13:57 UTC, ptntsv commented on Task_1_3_1/src/test/java/FindTest.java
> +public class FindTest {
Собственно, если попробовать считать содержимое файла в строку, тест падает с `OutOfMemory`.
![image](https://github.com/user-attachments/assets/4f6467e9-500e-4e9b-b5ec-e73af77f377b)

2024-11-12 06:51 UTC, Sharapov-Maksim requested changes
Почти зачтено, поправьте чуть-чуть

2024-11-12 06:51 UTC, Sharapov-Maksim commented on Task_1_3_1/src/main/java/org/example/Main.java
> +            System.err.println(e.getMessage());
Лучше убрать печать, если пользователю понадобится - распечатает. А то получается неописанный сайд-эффект

2024-11-12 07:06 UTC, ptntsv commented on Task_1_3_1/src/main/java/org/example/Main.java
> +            System.err.println(e.getMessage());
Done

2024-11-14 15:48 UTC, Sharapov-Maksim approved these changes
Задание зачтено, PR можно мёржить

2024-11-28 02:25 UTC, merged