Task_1_1_1
ptntsv/OOP pull request #7
Opened 2024-09-08 03:15 UTC by ptntsv

2024-09-09 16:42 UTC, Sharapov-Maksim requested changes
Замечания выдал, исправляйте, комментируйте, запрашивайте повторное ревью

2024-09-09 16:42 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/org/example/Heap.java
> +public class Heap {
Замечания CI надо исправлять, добавить javadoc

2024-09-09 16:42 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/org/example/Heap.java
> +     * Binary heap should maintain an invariant A[i] &lt;= A[i * 2 + 1] and A[i] &lt;= A[i * 2 + 2]
reviewdog ругается на отсутствие точки в конце

> 7.2 The summary fragment
> ... the fragment is capitalized and punctuated as if it were a complete sentence.
[link](https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)

2024-09-09 16:42 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/org/example/Heap.java
> +    private void siftDown(int i) {
Какая оценка сложности у такой реализации `siftDown`? Какова общая сложность предложенного вами решения? Как она соотносится к теоретической?

2024-09-09 16:42 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/org/example/Heap.java
> +public class Heap {
везде =)

2024-09-09 16:42 UTC, Sharapov-Maksim commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +    public void testAlreadySorted1() {
Названия `testAlreadySorted1`, `testAlreadySorted2` как-то противоречат содержимому тестов

2024-09-09 16:42 UTC, Sharapov-Maksim commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +    @BeforeEach
Зачем `@BeforeEach`? Результат используется всего в паре тестов.
Лучше переделать, чтобы `generate` возвращал готовый Heap при вызове, тогда можно будет звать его из нужных тестов, а от статической переменной `testHeap` можно избавиться.

2024-09-09 16:42 UTC, Sharapov-Maksim commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +        rand = new Random();
Не понятно, зачем иметь общий рандом на все тесты, если при каждом их запуске создаётся новый. Если хотите добиться воспроизводимости тестов, то стоит указать `seed` аргументом

2024-09-09 16:42 UTC, Sharapov-Maksim commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +        int[] data = new int[1000];
`1000` - неименованная константа, такие стоит выносить в `static final` переменные класса

2024-09-10 04:02 UTC, ptntsv commented on Task_1_1_1/src/main/java/org/example/Heap.java
> +    private void siftDown(int i) {
Худший случай -- куча является полным бинарным деревом и просеивать нужно до кроны (то есть log_2(n)) операций. Общая сложность решения: O(N) - построение кучи из массива, O(N * log2N) - сортируем пирамиду, и того, сложность пирамидальной сортировки O(N * log2N)

2024-09-10 04:13 UTC, ptntsv commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +        int[] data = new int[1000];
Исправлено

2024-09-10 04:13 UTC, ptntsv commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +        rand = new Random();
Исправлено

2024-09-10 04:13 UTC, ptntsv commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +    @BeforeEach
Исправлено

2024-09-10 04:13 UTC, ptntsv commented on Task_1_1_1/src/main/java/org/example/Heap.java
> +     * Binary heap should maintain an invariant A[i] &lt;= A[i * 2 + 1] and A[i] &lt;= A[i * 2 + 2]
Исправлено

2024-09-10 04:15 UTC, ptntsv commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +    public void testAlreadySorted1() {
Не понял в чем проблема, тесты покрывают случай, если в массиве все элементы находятся на своих местах кроме последнего и первого элементов соответственно. Просто не придумал как это лучше обозвать.

2024-09-10 06:22 UTC, Sharapov-Maksim requested changes

2024-09-10 06:22 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/org/example/Heap.java
> +    private void siftDown(int i) {
Я вижу в `siftDown` цикл [i, heapLen/2), в `extractMin` зовётся `siftDown(0)` и так N раз. Получается сложность `siftDown(0)` - O(N), сложность всего алгоритма O(N^2)

2024-09-10 06:22 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/org/example/Heap.java
> +    private void siftDown(int i) {
Обычно `siftDown` делают рекурсивным. Эту рекурсию можно развернуть в цикл, как у вас. Однако к `i++` у меня вопросы, вместо рекурсивного обхода дерева получился обход по всей верхушке (кроме листьев)

Жаль что на семинаре очно не получилось поговорить, это было бы легче

2024-09-10 09:10 UTC, ptntsv commented on Task_1_1_1/src/main/java/org/example/Heap.java
> +    private void siftDown(int i) {
Исправил

2024-09-10 09:11 UTC, ptntsv commented on Task_1_1_1/src/main/java/org/example/Heap.java
> +    private void siftDown(int i) {
Исправлено

2024-09-10 10:12 UTC, Sharapov-Maksim commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +    public void testAlreadySorted1() {
Ладно

2024-09-10 10:16 UTC, Sharapov-Maksim approved these changes
Замечания исправлены

2024-09-10 10:16 UTC, merged