Task_1_1_2
ptntsv/OOP pull request #9
Opened 2024-09-15 03:31 UTC by ptntsv

2024-09-15 07:45 UTC, Sharapov-Maksim requested changes
Доделывайте реализацию. Мягкий дедлайн зачтён

2024-09-15 07:45 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Game.java
> +            TimeUnit.SECONDS.sleep(1);
А зачем `sleep`?

2024-09-15 07:45 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Player.java
> +            this.score += 1;
Судя по правилам, стоимость **всех** тузов в руке уменьшается до 1, не забудьте про это.

Тестик на такой сценарий стоит тоже добавить

2024-09-15 07:45 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Player.java
> +        System.out.println("Вы выигрываете раунд! Счёт " + ++scoreTable[0] + ":" + scoreTable[1]);
Думаю `Player` не должен самостоятельно менять счёт, это ведь логика самой игры. Печатать сообщение тут тоже не уместно, вы же даже класс `IO` завели, так воспользуйтесь

2024-09-15 07:45 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Game.java
> +            if (player.getScore() >= dealer.getScore()) {
Бывает ничья ещё

2024-09-15 07:45 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Dealer.java
> +public class Dealer extends Player {
Здорово, что вы уже наследование используете)
Расскажите тогда, что такое наследование и почему вы здесь решили применить этот механизм?

2024-09-15 07:48 UTC, Sharapov-Maksim commented
Не стоит запрашивать ревью, а потом молча докомитывать правки. Сейчас так получилось, что правки приходили прямо во время ревью - не удобно

2024-09-15 08:17 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Game.java
> +            TimeUnit.SECONDS.sleep(1);
Чтобы было удобнее играть) А то в момент вываливается огромное полотно текста и не очень удобно.

2024-09-17 04:20 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Game.java
> +            if (player.getScore() >= dealer.getScore()) {
Исправлено

2024-09-17 04:20 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Player.java
> +        System.out.println("Вы выигрываете раунд! Счёт " + ++scoreTable[0] + ":" + scoreTable[1]);
Исправлено

2024-09-17 04:20 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Player.java
> +            this.score += 1;
Fixed

2024-09-17 04:24 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Dealer.java
> +public class Dealer extends Player {
Наследование - механизм, который позволяет переиспользовать код и выстраивать некоторую иерархию, в этом задании есть достаточно общая сущность Player, есть Dealer, который по сути тоже является игроком, то есть наследует некоторые методы и поля (карты в данный момент, счёт), но также у него есть доп. логика, которой нет у обычного игрока (метод dealCards, поле hasOpened) и т.д

2024-09-19 14:55 UTC, Sharapov-Maksim requested changes
Выдал очередные правки. Не забывайте поправить замечания checkstyle

2024-09-19 14:55 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Main.java
> +    public static void main(String[] args) {
пустой main

2024-09-19 14:55 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Game.java
> +                scoreTable[0]++;
Индексам `0` и `1` стоит присвоить имена, неименованные константы плохо читаются

2024-09-19 14:55 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Deck.java
> +public class Deck {
На колоду тесты надо сделать

2024-09-19 14:55 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Deck.java
> +    public void reset() {
Вижу сдесь добавления карт, но не вижу удаления старых...

Отличный сценарий для теста, я считаю

2024-09-19 14:55 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Game.java
> +            if (winState != WinState.NEITHER) {
Не понимаю смысла этих `if (winState != WinState.NEITHER)`, объясните?

2024-09-19 14:55 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Game.java
> +            case DRAW: {
Надо бы что-то тоже напечатать

2024-09-19 14:55 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Player.java
> +        while (input == 1) {
Константе `1` надо дать имя.

2024-09-19 14:55 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Player.java
> +        while (input == 1) {
А если пользователь введёт и не `1`, и не `0`, ход всё равно завершится. Хотя сообщение в начале хода этого не объясняет. Надо либо поправить сообщение, либо добавить обработку нажатия неправильных клавиш

2024-09-21 03:07 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Game.java
> +            case DRAW: {
Fixed

2024-09-21 03:28 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Player.java
> +        while (input == 1) {
Fixed

2024-09-21 03:28 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Player.java
> +        while (input == 1) {
Fixed

2024-09-21 03:28 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Game.java
> +            if (winState != WinState.NEITHER) {
Fixed

2024-09-21 03:35 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Game.java
> +                scoreTable[0]++;
Fixed

2024-09-21 03:35 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Main.java
> +    public static void main(String[] args) {
В ином случае градл в воркфлоу не билдится.

2024-09-21 05:06 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Deck.java
> +    public void reset() {
Added

2024-09-21 05:06 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Deck.java
> +public class Deck {
Added

2024-09-22 05:50 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Main.java
> +    public static void main(String[] args) {
С этим надо разобраться. Давайте добавим создание игры и запуск сюда, а то поиграть в игру сейчас невозможно, строго говоря. Если будут проблемы с workflow, посмотрим вместе на них

2024-09-22 06:47 UTC, Sharapov-Maksim requested changes
Выдал новые правки, не забудьте поправить замечания GitHub Actions / reviewdog

2024-09-22 06:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Game.java
> +            // TODO: remove
Надо бы доделать TODO

2024-09-22 06:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/DeckTest.java
> +    public void commonTest() throws DeckIsEmptyException {
Unit-тесты, по возможности нужно делать как можно меньше, тестировать в каждом мальеньком тесте только чатсть функциональности. Этот тест можно разбить, как минимум, на два: создание `Deck`, использование `reset`.

Дробление на маленькие тесты помогает при отладке, в случае когда часть тестов упала, легче определить scope проблемы

2024-09-22 06:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Card.java
> +    public String toString() {
добавить тесты

2024-09-22 06:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/CardType.java
> +    private final String toStr;
название поля неудачное, лучше что-нибудь вроде `name`

2024-09-22 06:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/CardType.java
> +    private final String toStr;
и аналогично с `org.example.Suit#toStr`

2024-09-22 06:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Game.java
> +    private void newRound() {
сделать тест

2024-09-22 06:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Game.java
> +    final private Deck deck = new Deck();
См. [code style](https://google.github.io/styleguide/javaguide.html#s4.8.7-modifiers)

2024-09-22 06:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Player.java
> +    public String printCardsMsg() {
Название метода не соответствует сути, слово `print` надо бы заменить

2024-09-22 06:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Player.java
> +    public String printCardsMsg() {
Добавить тесты

2024-09-22 06:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Dealer.java
> +    public void dealCards(Deck deck, Player player) throws InvalidTurnException {
Добавить тесты

2024-09-23 11:07 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Dealer.java
> +    public void dealCards(Deck deck, Player player) throws InvalidTurnException {
А нельзя сослаться на то, что по сути в этом методе вызываются методы, которые уже раннее протестированы (`peekCard()` у `Player` это просто обертка над `peekCard()` в `Deck` (который протестирован в `DeckTest` как и `updateScore()`, так же раннее покрыт тестами случай, когда `peekCard()` у `Deck` выбрасывает `DeckIsEmptyException`) ?

2024-09-23 11:08 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Player.java
> +    public String printCardsMsg() {
Fixed

2024-09-23 11:08 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Player.java
> +    public String printCardsMsg() {
Done

2024-09-23 11:08 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Game.java
> +    private void newRound() {
Done

2024-09-23 11:08 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/CardType.java
> +    private final String toStr;
Done

2024-09-23 11:08 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Card.java
> +    public String toString() {
Done

2024-09-23 11:08 UTC, ptntsv commented on Task_1_1_2/src/test/java/DeckTest.java
> +    public void commonTest() throws DeckIsEmptyException {
Done

2024-09-23 11:08 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Game.java
> +            // TODO: remove
Done

2024-09-23 16:56 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/GameTest.java
> +        newRoundMethod.setAccessible(true);
Можно было просто метод пометить `protected`, чтобы не лезть в Reflection API

2024-09-23 16:56 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Dealer.java
> +    public void dealCards(Deck deck, Player player) throws InvalidTurnException {
Вызов протестированых методов содержит в себе какую-то логику, её и надо протестировать, пусть даже одним простым тестом.

Ну и покрытие говорит само за себя
![image](https://github.com/user-attachments/assets/d1eb5690-8365-455f-820f-f684bee192ba)

2024-09-23 17:03 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Dealer.java
> +    public void dealCards(Deck deck, Player player) throws InvalidTurnException {
Не тестировать можно приватные методы, которые зовутся из протестированных методов. Тогда приватные будут тоже покрыты и, так как они приватные и не являются частью API класса, отдельные тесты не требуются, но и не запрещаются.

2024-09-23 17:23 UTC, Sharapov-Maksim requested changes

2024-09-23 17:23 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Dealer.java
> +    public void takeTurn(Deck deck, Game gameContext) throws InvalidTurnException {
Сделать тесты

2024-09-23 17:23 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/org/example/Card.java
> +        Card other = (Card) obj;
При таком приведении типов (downcast) возможно возникновение исключительной ситуации, когда реальный тип объекта не является наследником требуемого (`ClassCastException`). Однако в javadoc `java.lang.Object#equals` нет упоминания исключений, такую ситуацию надо корректно обрабатывать.
Для этого обычно выполняют проверку типов и если типы не сходятся, то возвращают `false`. 
Пример из `java.lang.Integer#equals`:
```
    public boolean equals(Object obj) {
        if (obj instanceof Integer) {
            return value == ((Integer)obj).intValue();
        }
        return false;
    }
```

2024-09-23 17:23 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/DeckTest.java
> +                flag = true;
А если последняя карта в `d` совпадёт с последней картой в `unshuffled`?

Лучше будет сохранить колоду, сделать ещё один вызов `reset` и проверить что хотя бы один элемент не на том же месте, что был раньше. Так как тут мы имеем дело с рандомом, большего требовать было бы неправильно

2024-09-24 01:15 UTC, ptntsv commented on Task_1_1_2/src/test/java/DeckTest.java
> +                flag = true;
Вроде бы я делаю тоже самое, `else` же нет никакого или я туплю..

2024-09-24 01:15 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Card.java
> +        Card other = (Card) obj;
Done

2024-09-24 01:15 UTC, ptntsv commented on Task_1_1_2/src/main/java/org/example/Dealer.java
> +    public void takeTurn(Deck deck, Game gameContext) throws InvalidTurnException {
Done

2024-09-24 01:17 UTC, ptntsv commented on Task_1_1_2/src/test/java/GameTest.java
> +        newRoundMethod.setAccessible(true);
Немного не разобрался как его прикрутить, беглым гуглежом понял, что он позволяет доступаться дочерним классам из одного/разных package, но для класса теста ни то ни то не верно, получается надо как-то засовывать тесты в тот же package, что и сурцы?

2024-09-24 04:20 UTC, Sharapov-Maksim approved these changes

2024-10-01 04:42 UTC, closed without merging